# .github/workflows/ci.yml
name: Python CI with Pixi

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      # 👇 Use the official GitHub action to install and cache Pixi
      uses: prefix-dev/setup-pixi@v0.9.1
      with:
        pixi-version: v0.55.0 # Pin the version for consistency

    - name: Install dependencies
      # 👇 pixi install uses the lockfile for a fast, reproducible install
      run: pixi install

    - name: Lint with ruff
      # 👇 Run the lint task defined in pixi.toml
      run: pixi run lint

    - name: Test with pytest
      # 👇 Run the test task defined in pixi.toml
      run: pixi run test
